In [3]:
import numpy as np

In [4]:
arr1= np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr2=np.array([[1,2,4,3],[5,6,7,8]])
arr2

array([[1, 2, 4, 3],
       [5, 6, 7, 8]])

In [9]:
arr2.shape

(2, 4)

In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.shape

(2, 3)

In [19]:
arr.ndim

2

In [20]:
arr.dtype

dtype('int32')

In [21]:
arr.itemsize


4

In [22]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]


In [26]:
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [27]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [28]:
arr=np.array([[1,2,3,4],[4,5,6,7],[7,9,8,10]])

In [29]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  9,  8, 10]])

In [35]:
print(arr[1:,1:])

[[ 5  6  7]
 [ 9  8 10]]


In [36]:
arr[0][0]

1

In [37]:
arr[0:2,2:]

array([[3, 4],
       [6, 7]])

In [38]:
arr[1:,2:]

array([[ 6,  7],
       [ 8, 10]])

In [41]:
arr[0,0]=100

In [42]:
arr

array([[100,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   9,   8,  10]])

In [43]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [44]:
mean=np.mean(arr1)
mean

3.0

In [45]:
np.median(arr1)

3.0

In [48]:
normalized_data=(arr1-mean)


In [49]:
np.var(arr1)

2.0